unique_name: dataset_ModelSettings
object_type: dataset
label: ModelSettings
columns:
  - name: CalendarID
    data_type: long
  - name: ForecastHistoryCutoffDate
    data_type: datetime
  - name: NetIncomeCutoffDate
    data_type: datetime
  - name: CurrentYearLM
    data_type: double
  - name: MaxStartDate
    data_type: datetime
  - name: PFMETCStartDate
    data_type: datetime
  - name: PFMCDBGLMonth
    data_type: datetime
  - name: countrows1
    data_type: int
    sql: '1'
connection_id: SQL42
sql: >-
  select CalendarID, ForecastHistoryCutoffDate, NetIncomeCutoffDate,
  CurrentYearLM, PFMETCStartDate, PFMCDBGLMonth, maxstartdate.MaxStartDate from
  SISOT.dbo.PSMSettings cross join ( SELECT MAX(MAX_START_DATE) AS MaxStartDate
  FROM (SELECT MAX(START_DATE) AS MAX_START_DATE FROM
  AnalyticsSource.dbo.FINANCIAL_PLAN_LINES UNION SELECT MAX(START_DATE) AS
  MAX_START_DATE FROM AnalyticsSource.east.FINANCIAL_PLAN_LINES ) md )
  maxstartdate
